### ISSUE TITLE
Error when building release

### ISSUE THREAD

**Issue by The-Mr-L** [amrbashir/vite-plugin-tauri#1]
Hi, I think you have to remove the '"./" +' from the dist path resolve. thank you

15:46:24 PM [vite-plugin-tauri]  tauri-cli_windows.exe download Completed.
Error: Unable to find your web assets, did you forget to build your web app? Your distDir is set to ""../C:\\Users\\xxxx\\projects\\app\\project\\dist""

edit 
well I tried removing it  and now it builds but the ui is just blank not rendering. I  am on windows 10.  I tried debug build and same thing happens and no error messages  in the ui or backend

**Comment by amrbashir** [comment]
v0.1.11 is published with the fix. Unfortunately wasn't able to test it so let me know if it works.

**Comment by The-Mr-L** [comment]
thx, now it builds. but it is just a white page app. this might not be a problem related to this project, so please do a test you self when you have time. I will debug it some more

**Comment by The-Mr-L** [comment]
Okay it turns out doing the following fixes the problem

```
config: {
      build: {
        distDir: "../dist",//(await resolveConfig({}, "build", "production")).build.outDir
      }
    }
```
so now you know as well ;) I have not found the reason for this. but you must have had a reason not to hard code the path like this right?

**Comment by amrbashir** [comment]
I am currently away for another two weeks and can't test this. I am trying to fix this on my phone on the go.

I can't hardcode `../dist` because users can change that in `vite.config.js`.

Anyways I will publish version v0.1.12 with the fix (hopefully).

Edit: v0.1.12 is published now

**Comment by The-Mr-L** [comment]
Thanks again  :) it works now. Hope you have not stressed yourself too hard

**Comment by amrbashir** [comment]
Not at all, thanks for reporting back.
