### ISSUE TITLE
Support Tauri plugin and Vite Library mode

### ISSUE THREAD

**Issue by h7kanna** [amrbashir/vite-plugin-tauri#11]
It will be good to have support for creating the [Tauri plugin](https://tauri.app/v1/guides/features/plugin).

We can create libraries using Vite [Library mode](https://vitejs.dev/guide/build.html#library-mode)

Currently, the Tauri plugins have only a rollup config-based template. 

Example https://github.com/tauri-apps/tauri-plugin-store

Basically, integrate the Tauri plugin into TS/JS library when in Vite library mode.

**Comment by amrbashir** [comment]
I am not quite sure what exactly do you want so would you mind explaining a bit more, possible with a code example of this hypothetical feature/

**Comment by h7kanna** [comment]
Hi, Sorry for not being clearer.
After spending some time with this plugin since I created the ticket, I realized that the feature I was asking for may not be relevant to this package.

But here is a bit more explanation.

This plugin helps in adding 'Tauri' into a Vite UI project.

But we can also develop individual Tauri plugin projects. 
They contain both a Javascript client and a Rust interface. Currently, there are examples of Tauri plugins as I linked above. They use rollup config to build JS client module. 
Instead, we can use 'Vite'. That means in the reverse direction. 
We have a Rust cargo project, and then we can add Vite(library mode) to it and convert it into a Tauri plugin.

An example Tauri plugin's Vite config and package json

vite.config.js
``` js 
import { defineConfig } from 'vite';
import { resolve } from 'path';
import dts from 'vite-plugin-dts';

export default defineConfig({
	build: {
		lib: {
			entry: resolve(__dirname, 'webview-src/index.ts'),
			name: 'tauri-plugin-example-api',
			fileName: 'index'
		},
		outDir: 'webview-dist'
	},
	plugins: [dts()]
});
```
package json

```
{
	"name": "tauri-plugin-example-api",
	"version": "0.0.1",
	"author": "You",
	"description": "Example as Tauri Plugin",
	"browser": "webview-dist/index.js",
	"type": "module",
	"license": "MIT",
	"scripts": {
		"build": "rm -rf ./webview-dist && vite build",
		"prepublishOnly": "yarn build",
		"pretest": "yarn build",
		"lint": "prettier --plugin-search-dir . --check . && eslint .",
		"format": "prettier --plugin-search-dir . --write ."
	},
	"devDependencies": {
		"@typescript-eslint/eslint-plugin": "^5.59.8",
		"@typescript-eslint/parser": "^5.59.8",
		"eslint": "^8.42.0",
		"eslint-config-prettier": "^8.8.0",
		"prettier": "^2.8.8",
		"typescript": "5.1.3",
		"vite": "^4.3.9",
		"vite-plugin-dts": "^2.3.0"
	},
	"dependencies": {
		"@tauri-apps/api": "^1.4.0",
		"tslib": "^2.5.3"
	},
	"files": [
		"webview-dist"
	],
	"main": "webview-dist/index.umd.cjs",
	"module": "webview-dist/index.js",
	"types": "webview-dist/index.d.ts",
	"exports": {
		".": {
			"types": "./webview-dist/index.d.ts",
			"import": "./webview-dist/index.js",
			"require": "./webview-dist/index.umd.cjs"
		}
	}
```

**Comment by amrbashir** [comment]
yeah this sounds like something out of this plugin scope, what you need is to just replace the rollup setup of your pluing (created with the tauri CLI or from scratch) with vite library mode.
