### ISSUE TITLE
cant build after update 

### ISSUE THREAD

**Issue by The-Mr-L** [amrbashir/vite-plugin-tauri#2]
hey I think the problem is related to this project ?

```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'C:\Users\xxxx\Desktop\project\app\x\node_modules\.pnpm\vite-plugin-tauri@1.1.0_a51533014e25e427fd41fc3dc0737403\node_modules\@tauri-apps\cli\main' imported from C:\Users\xxxx\Desktop\project\app\x\node_modules\.pnpm\vite-plugin-tauri@1.1.0_a51533014e25e427fd41fc3dc0737403\node_modules\vite-plugin-tauri\bin\vite-tauri.js
Did you mean to import @tauri-apps+cli@1.0.0-rc.5/node_modules/@tauri-apps/cli/main.js?
    at new NodeError (internal/errors.js:322:7)
    at finalizeResolution (internal/modules/esm/resolve.js:308:11)
    at moduleResolve (internal/modules/esm/resolve.js:731:10)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:842:11)
    at Loader.resolve (internal/modules/esm/loader.js:89:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:76:40)
    at link (internal/modules/esm/module_job.js:75:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
 ELIFECYCLE  Command failed with exit code 1.
```

I am using:
Deps:
    "@tauri-apps/api": "^1.0.0-rc.1",
DevDeps:
    "vite-plugin-tauri": "^1.1.0",
    "@tauri-apps/cli": "^1.0.0-rc.5",

**Comment by amrbashir** [comment]
Can you provide a minimal repro or steps to produce? I will try to look into this asap.

**Comment by amrbashir** [comment]
Fixed in v1.1.1

**Comment by The-Mr-L** [comment]
hi, well now I get this
 [vite-plugin-tauri]  Starting Tauri...
thread '<unnamed>' panicked at 'Couldn't recognize the current folder as a Tauri project. It must contain a `tauri.conf.json` or `tauri.conf.json5` file in any subfolder.', src\helpers\app_paths.rs:64:4
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

It seams we not in src-tauri?

**Comment by The-Mr-L** [comment]
when I run dev

**Comment by amrbashir** [comment]
This looks like an issue with tauri's cli and not the plugin.

Can you show your folder structure just to be sure?

**Comment by The-Mr-L** [comment]
yes, my project folder is  
dist
node_modules
public
srs
src-tauri

**Comment by The-Mr-L** [comment]
well if this is not an issue with this project then thank you for fixing the first* step :)

**Comment by The-Mr-L** [comment]
okay I tried moving the tauri.conf.json to the root foler of the project and I get this
[vite-plugin-tauri]  Error: Input watch path is neither a file nor a directory.
