### ISSUE TITLE
stdout prints buffer instead of utf8

### ISSUE THREAD

**Issue by LambdaMan2K** [amrbashir/vite-plugin-tauri#29]
Hi, as requested I report the issue which might be related to this plugin.
ref https://github.com/tauri-apps/tauri/issues/3056.
just tell me if there is something I should test, thank you.

**Comment by amrbashir** [comment]
version 0.1.10 is published with the fix.

**Comment by LambdaMan2K** [comment]
Indeed it works now, thank you!
