### ISSUE TITLE
HMR not reloading on wsl2 docker environment

### ISSUE THREAD

**Issue by moracabanas** [amrbashir/vite-plugin-tauri#3]
Vite HMR works on browser by setting up `vite.config.js` 
```js
export default defineConfig({
  server: {
    hmr: {
      host: '0.0.0.0'
    }
  }
}
```

but when I use `yarn vite-tauri dev` app works good but HMR does not hot reload tauri web view

**Comment by amrbashir** [comment]
Can you share more info about your setup? Are you running docker inside wsl2? if you can, provide a minimal repro.
