### ISSUE TITLE
Evolve into Vite plugin

### ISSUE THREAD

**Issue by probablykasper** [amrbashir/vite-plugin-tauri#8]
Ironically this doesn't seem to be a vite plugin, would be nice to turn it into one

For reference, an Electron vite plugin I made: https://github.com/probablykasper/vite-plugin-electron-x (though it's probably a lot more complex than what a tauri plugin would need to be)

**Comment by amrbashir** [comment]
I wanted to do that when I first wrote the plugin but tbh I don't remember why it didn't work at the time. I will look into this again. It should be simple.

**Comment by amrbashir** [comment]
Thanks for the suggestion @probablykasper and for your awesome repo. It is published now.

**Comment by kasper9n** [comment]
Oh nice, that was quick
